# Generated by telegram-socks5-proxy.
# Fallback config used before the API writes the real runtime config.

pidfile __PIDFILE_PATH__
log __LOG_PATH__
logformat "L%Y-%m-%d %H:%M:%S __SERVICE_NAME__ %N %E %C:%c %R:%r %I/%O %T"
nscache 65536
nserver __PRIMARY_RESOLVER__
nserver __SECONDARY_RESOLVER__
monitor /data/3proxy.cfg
auth strong
flush
deny *
socks -p__SOCKS5_PORT__ -i__BIND_ADDRESS__
